/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wsclient;

import javax.swing.JOptionPane;

/**
 *
 * @author Алексей
 */
public class ChatFrame extends javax.swing.JFrame {

    private ChatFrame.EventHandler listener;
    private boolean isLogin = false;
    
    /**
     * Creates new form ChatFrame
     */
    public ChatFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        areaMessages.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaMessages = new javax.swing.JTextArea();
        textMessage = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaUsers = new javax.swing.JTextArea();
        labelMe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Чат-клиент");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        areaMessages.setEditable(false);
        areaMessages.setColumns(20);
        areaMessages.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        areaMessages.setRows(5);
        areaMessages.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaMessages);

        textMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMessageKeyPressed(evt);
            }
        });

        btnEnter.setText("Войти");
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        areaUsers.setColumns(20);
        areaUsers.setRows(5);
        jScrollPane2.setViewportView(areaUsers);

        labelMe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textMessage, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnter)
                    .addComponent(labelMe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMessageKeyPressed

        String message = textMessage.getText();
        
        if (evt.getKeyCode() != java.awt.event.KeyEvent.VK_ENTER)
            return;

        if(message.equals(""))
            return;         
        
        textMessage.setText("");
        
        if(this.listener != null)
            this.listener.sendMessage(message);
        
    }//GEN-LAST:event_textMessageKeyPressed

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        
        if(this.listener == null)
            return;
        
        if(this.isLogin) {
            this.listener.clickSignOut();
        } else {
            this.listener.clickSignIn();
        }       
        
    }//GEN-LAST:event_btnEnterMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if(this.listener != null)
            this.listener.clickExit();        
        
    }//GEN-LAST:event_formWindowClosing

    
    public void addMessage(String line) {
        areaMessages.append(line + "\n");
        areaMessages.setCaretPosition(areaMessages.getDocument().getLength());
    }
    
    public void addUser(Hitagi.User user) {

    
    }
    
    public void removeUser(Hitagi.User user) {

    
    }
    
    public void setMe(Hitagi.User me) {

        labelMe.setText(me.nick + " (" + me.login + ")");
        btnEnter.setText("Выход");
        this.isLogin = true;
        
    }
    
    public void unsetMe() {

        labelMe.setText("");
        btnEnter.setText("Войти");
        this.isLogin = false;
    
    }
    
    
    public void setListener (EventHandler listener){
        this.listener = listener;
    }
    
    public static interface EventHandler {
        public void sendMessage(String message);
        public void clickSignIn();
        public void clickSignOut();
        public void clickExit();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMessages;
    private javax.swing.JTextArea areaUsers;
    private javax.swing.JButton btnEnter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMe;
    private javax.swing.JTextField textMessage;
    // End of variables declaration//GEN-END:variables
}
